name: CI

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:
    name: Build Workflow
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout first
        uses: actions/checkout@v2
      - name: yarn install, build, and test
        run: |
          yarn
          yarn build
      - name: Extract artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Artifacts
          path: ./dist

